## Travis config file to build a package

language: r
cache: packages
r:
  - release
  - devel
before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev
after_success:
  - Rscript -e 'covr::codecov()'
