## Travis config file to build a package

language: r

cache: packages

r:
  - release
  - devel

before_install:
  - sudo apt-get update
  - sudo apt-get install libfftw3-dev libgsl-dev
  - export NOT_CRAN="true"
  
script:
  # Test first fitting results against pli code
  - R -e "install.packages(c('devtools', 'testthat'))"
  - R -e "TEST_PSDFIT <- TRUE; devtools::test(filter = 'test-psdfit')"
  - R -e "TEST_XMIN <- TRUE; devtools::test(filter = 'test-xmin')"
  # Then test the whole package
  - R CMD build .
  - R CMD check *tar.gz
  
after_success:
  - Rscript -e 'covr::codecov()'
  
after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
